version: '3'
services: 
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /frontend/node_modules
      - .:/frontend
  frontend-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /frontend/node_modules
      - .:/frontend
    command: ["npm", "run", "test"] 